mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('students.urls')),
    path('admin/', admin.site.urls),
    path('tutors/', include('tutors.urls')),
    url(r'^accounts/', include('allauth.urls')),
]

students/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'students'
urlpatterns = [
    path('', views.landing, name='landing'),
    path('students/rating', views.rating, name='ratings'),
    path('students/edit', views.edit_form, name='student_edit'),
    path('students/logout', views.logoutview, name='logout'),
    path('students/', views.home, name='home'),
    path('students/signup', views.signup_form, name='signup_form'),
    path('students/profile', views.ProfileView.as_view(), name='profile'),
    path('students/choose', views.choose_signup, name='choose_signup'),
    path('students/signin', views.sign_in_as, name='sign_in_as'),
    path('students/requests', views.request_view, name='request_view'),
    path('students/profile/<str:username>', views.ProfileView.as_view(), name='profile'),
    path('students/request_close/', views.request_close, name='request_close')
]

tutors/urls.py
from django.urls import path
from . import views

app_name = 'tutors'

urlpatterns = [
    path('edit', views.edit_form, name='edit'),
    path('', views.home, name='home'),
    path('logout', views.logoutview, name='logout'),
    path('profile/<str:username>', views.ProfileView.as_view(), name='profile'),
    path('profile', views.ProfileView.as_view(), name='myprofile'),
    path('signup', views.signup_form, name='signup'),
    path('activate', views.activate, name='activate'),
    path('deactivate', views.deactivate, name='deactivate'),
    path('send_request/<str:username>', views.send_request, name='request'),
    path('requests', views.request_view, name='request_view'),
    path('request_action/', views.request_action, name='request_action'),
    path('request_close/', views.request_close, name='request_close')
]

students/models.py
from django.db import models
from django.conf import settings
from django import forms


class StudentSignup(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=500, default="")
    phone_number = models.CharField(max_length=12, default="")
    classes = models.TextField(max_length=120, default="")

    def __str__(self):
        if self.phone_number==None:
            return "ERROR-NO PHONE NUMBER"
        return self.phone_number

students/forms.py
from django import forms
 
from .models import StudentSignup
 
 
class StudentSignupForm(forms.ModelForm):
    class Meta:
        model = StudentSignup
        fields = ('name', 'phone_number', 'classes')
        required = ('name', 'phone_number', 'classes')
        labels = {
        "phone_number": "Phone Number",
        "classes": "Classes (ex. CS 3240, CS 2150)",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

students/views.py
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.views import generic
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import StudentSignup
from tutors.models import TutorSignup, Request
from django.contrib import messages
from .forms import StudentSignupForm
from django.shortcuts import redirect
from django.contrib.auth.models import User

def landing(request):
    if request.user.is_authenticated:
        signed_in = 'yes'
    else:
        signed_in = "no"
    try:
        user = StudentSignup.objects.get(user=request.user)
        student = 'yes'
    except:
        student = 'no'
    try:
        user = TutorSignup.objects.get(user=request.user)
        tutor = 'yes'
    except:
        tutor = 'no'
    return render(request, 'students/landing.html', {"sign_in":signed_in, 'student':student,'tutor':tutor}) 
    #small change

@login_required(login_url='students:landing')
def rating(request):
    return render(request, 'students/ratings')

# getting the secret access token from .env file
from dotenv import load_dotenv
load_dotenv()
import os
ACCESS_TOKEN = os.getenv("ACCESS_TOKEN")

@login_required(login_url='students:landing')
def home(request):
    tutors = TutorSignup.objects.all()
    active_tutors = []
    tutor_coords = []
    for tutor in tutors:
        if tutor.status == True:
            active_tutors.append(tutor)
    # only passing active tutor info into home template
    for active_tutor in active_tutors:
        longitude = active_tutor.longitude
        tutor_long = float(longitude)
        latitude = active_tutor.latitude
        tutor_lat = float(latitude)
        coords = '{"longitude": tutor_long, "latitude": tutor_lat, "phone": active_tutor.phone_number, "name": active_tutor.user.username}'
        final_coords = eval(coords)
        tutor_coords.append(final_coords)
    return render(request, 'students/home.html', {'ACCESS_TOKEN': ACCESS_TOKEN, 'tutors_list': tutor_coords}) 

def logoutview(request):
    logout(request)
    return redirect('students:landing')

@login_required(login_url='students:landing')
def edit_form(request):
    if request.method == 'POST':
        name = request.POST['name']
        phone = request.POST['phone_number']
        classes = request.POST['classes']
        user = StudentSignup.objects.get(user=request.user)
        user.name = name
        user.phone_number = phone
        user.classes = classes
        user.save()
        return redirect('/students/profile')
    else:
        form = StudentSignupForm()
    return render(request, 'students/edit.html', {'form': form})

@login_required(login_url='students:landing')
def signup_form(request):
    if request.method == 'POST':
        form = StudentSignupForm(request.POST)
        try:
            user = StudentSignup.objects.get(user=request.user)
            messages.error(request,'Student Account Already Exists For This User!')
            return redirect('/students/signup')
        except StudentSignup.DoesNotExist:
            if form.is_valid():
                name = request.POST['name']
                phone = request.POST['phone_number']
                classes = request.POST['classes']
                user_object = StudentSignup.objects.create(user=request.user, name = name, phone_number = phone, classes = classes)
                user_object.save()
            return HttpResponseRedirect('/students')
    else:
        form = StudentSignupForm()
    return render(request, 'students/signup.html', {'form': form}) 

@login_required(login_url='students:landing')
def choose_signup(request):
    try:
        user = StudentSignup.objects.get(user=request.user)
        student = 'yes'
    except:
        student = 'no'
    try:
        user = TutorSignup.objects.get(user=request.user)
        tutor = 'yes'
    except:
        tutor = 'no'
    return render(request, 'students/choose.html', {'student':student,'tutor':tutor})

@login_required(login_url='students:landing')
def sign_in_as(request):
    try:
        user = StudentSignup.objects.get(user=request.user)
        student = 'yes'
    except:
        student = 'no'
    try:
        user = TutorSignup.objects.get(user=request.user)
        tutor = 'yes'
    except:
        tutor = 'no'
    return render(request, 'students/sign_in_as.html', {'student':student,'tutor':tutor})

class ProfileView(LoginRequiredMixin, generic.ListView):
    login_url = 'students:landing'
    redirect_field_name = 'redirect_to'
    template_name = 'students/profile.html'
    context_object_name = 'profile_list'

    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)
            user = TutorSignup.objects.get(user=self.request.user)
            context['hasother'] = 'yes'
            return context
        except:
            context['hasother'] = 'no'
            return context

    def get_queryset(self):
        try:
            request_user = User.objects.get(username=self.kwargs['username'])
            return StudentSignup.objects.filter(user=request_user)
        
        except:
            return StudentSignup.objects.filter(user=self.request.user)

@login_required(login_url='students:landing')
class TutorProfileView(generic.ListView):
    template_name = 'tutors/profile.html'
    context_object_name = 'profile_list'

    def get_queryset(self):
        return StudentSignup.objects.filter(user=self.request.user)

@login_required(login_url='students:landing')
def request_view(request):
    template_name = 'students/requests.html'
    context_object_name = 'requests_list'

    requests = Request.objects.filter(student=request.user).order_by('-time')

    return render(request, 'students/requests.html', {'requests_list': requests}) 

@login_required(login_url='students:landing')
def request_close(request):
    if request.method == 'POST':
        request_id = int(request.POST['requ'])
        rate = int(request.POST['options'])
        specific_request = Request.objects.get(pk=request_id)
        if rate == 6:
            specific_request.delete()
            return HttpResponseRedirect('/students/requests')
        tutor_ratee = TutorSignup.objects.get(user=specific_request.tutor)
        if tutor_ratee.rating != None:
            tutor_ratee.rating = (((float(tutor_ratee.rating) * tutor_ratee.num_rates)) + rate) /  (tutor_ratee.num_rates + 1)
            tutor_ratee.num_rates +=1
        else:
            tutor_ratee.rating = rate
            tutor_ratee.num_rates += 1
        tutor_ratee.save()
        specific_request.delete()
        return HttpResponseRedirect('/students/requests')

students/templates/students/layout.html
<html>
  {% load static %}
  <head>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'students/format.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css"
      rel="stylesheet"
      id="bootstrap-css"
    />
  </head>
  <div id="page">
    <div id="wrapper">
      <header class="polls-header">
          <div class="flex-grid">
            <div class="col1">
              <a href="/students">
                <img src="/../static/images/logo.jpg" width="50" height="50" alt="">
              </a>
            </div>
            <div class="col1">          
              <nav class="navbar navbar-light" style="background-color: #ffffff;">
              <a class="nav-link" href="/students"><h4>Home</h4></a>
              <a class="nav-link" href="{% url 'students:request_view' %}"
              ><h4>
                Requests
              </h4></a
              >
              <a class="nav-link" href="{% url 'students:profile' user.username %}"
              ><h4>
                Student Profile
              </h4></a
              >
              </nav>
            </div>
            <div class="col3">
            <nav class="navbar navbar-light" style="background-color: #ffffff;">
              {% if user.is_authenticated %}
                <form action="{% url 'students:logout'%}">
                  <button class="btn btn-outline-success my-2 my-sm-0" href="{% url 'students:logout'%}"
                    ><h4>
                      Logout
                    </h4></a
                  >
                </form>
              {% endif %}
            </nav>
          </div>
        </div>
      </header>
      <br />
      <body id="body">
        {% block content %} {% endblock %}
      </body>
    </div>
  <footer>
    <div>Quick Tutor | @ 2020</div>
    <a>Contact: 1-800-234-1234</a>
  </footer>
</html>

students/templates/students/profile.html
<html>
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'students/format.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css"
      rel="stylesheet"
      id="bootstrap-css"
    />
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Student Profile</title>
  </head>
  {% if profile_list %}
  {% for p in profile_list %}
    {% if user.username == p.user.username %}
  <header class="polls-header">
    <div class="flex-grid">
      <div class="col1">
        <a href="/students">
          <img src="/../static/images/logo.jpg" width="50" height="50" alt="" />
        </a>
      </div>
      <div class="col1">
        <nav class="navbar navbar-light" style="background-color: #ffffff;">
          <a class="nav-link" href="/students"><h4>Home</h4></a>
          <a class="nav-link" href="{% url 'students:request_view' %}"
            ><h4>
              Requests
            </h4></a
          >
          <a class="nav-link" href="{% url 'students:profile' user.username %}"
            ><h4>
              Student Profile
            </h4></a
          >
        </nav>
      </div>
      <div class="col3">
        <nav class="navbar navbar-light" style="background-color: #ffffff;">
          {% if user.is_authenticated %}
            <form action="{% url 'students:logout'%}">
              <button class="btn btn-outline-success my-2 my-sm-0" href="{% url 'students:logout'%}"
                ><h4>
                  Logout
                </h4></a
              >
            </form>
          {% endif %}
        </nav>
      </div>
    </div>
  </header>
  <br />
  <body>
    <div id="wrapper">
      <body id="body">
    <div id="profile">
      <!-- Modal Stuff -->
      <div class="modal" id="edit">
        <div class="modal-dialog">
          <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Edit Profile</h4>
              <button type="button" class="close" data-dismiss="modal">
                &times;
              </button>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
              <form id="edit" role="form" method="POST" action="/students/edit">
                {% csrf_token %} {% for p in profile_list %}
                <div class="form-group">
                  <label class="name">Name</label>
                  <div>
                    <input
                      type="text"
                      class="form-control input-lg"
                      name="name"
                      value="{{p.name}}"
                    />
                  </div>
                </div>
                <div class="form-group">
                  <label class="phone_number">Phone Number</label>
                  <div>
                    <input
                      type="text"
                      class="form-control input-lg"
                      name="phone_number"
                      value="{{p.phone_number}}"
                    />
                  </div>
                </div>
                <div class="form-group">
                  <label class="classes">Classes</label>
                  <div>
                    <input
                      type="text-box"
                      class="form-control input-lg"
                      name="classes"
                      value="{{p.classes}}"
                    />
                  </div>
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-success">
                  Make Changes
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <script>
        $("#edit").on("hide.bs.modal", function () {
          location.reload();
        });
      </script>

      {% if profile_list %}
      <ul class="list-group">
        {% for p in profile_list %}
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">
              <h4 style="text-align: center;">
                {{p.name}}
              </h4>
            </h3>
          </div>
          <div
            class="col-md-3 col-lg-3"
            align="center"
            style="margin-top: 2rem; margin-bottom: 2rem;"
          >
            <img
              src="{{ user.socialaccount_set.all.0.get_avatar_url }}"
              height="150"
              width="150"
            />
          </div>
          <div class="col-md-9 col-lg-9" style="margin-top: 2rem;">
            <table class="table table-user-information">
              <tbody>
                <tr>
                  <td style="text-align: center;">Classes:</td>
                  <td style="text-align: center;">{{p.classes}}</td>
                </tr>
                <tr>
                  <td style="text-align: center;">Phone Number:</td>
                  <td style="text-align: center;">{{p.phone_number}}</td>
                </tr>
                <tr>
                  <td></td>
                  <td align="right">
                    <!--Modal button-->
                    {% if hasother == 'yes' %}
                    <a
                      style="margin-top: 1rem;"
                      type="button"
                      class="btn btn-primary"
                      href="{% url 'tutors:myprofile' %}"
                      >Tutor Profile</a
                    >
                    {%else%}
                    <a
                      style="margin-top: 1rem;"
                      type="button"
                      class="btn btn-primary"
                      href="{% url 'tutors:signup' %}"
                      >Make Tutor Profile</a
                    >
                    {%endif%}
                    <button
                      style="margin-top: 1rem;"
                      type="button"
                      class="btn btn-success"
                      data-toggle="modal"
                      data-target="#edit"
                    >
                      Edit Profile
                    </button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        {% endfor %}
      </ul>
      {% else %}
      <p>Your profile isn't in the database.</p>
      {% endif %}
    </div>
  </body>
</div>
<footer id="pfooter">
  <div>Quick Tutor | @ 2020</div>
  <a>Contact: 1-800-234-1234</a>
</footer>
{% else %} 
<header class="polls-header" style="margin-bottom: 4rem;">
  <div class="flex-grid">
    <div class="col1">
      <a href="/tutors">
        <img src="/../static/images/logo.jpg" width="50" height="50" alt="">
      </a>
    </div>
</div>
</header>  
<div id="wrapper">
  <body id="body">
<div id="profile">
  <!-- Modal Stuff -->
  <div class="modal" id="edit">
    <div class="modal-dialog">
      <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Edit Profile</h4>
          <button type="button" class="close" data-dismiss="modal">
            &times;
          </button>
        </div>
        <!-- Modal body -->
        <div class="modal-body">
          <form id="edit" role="form" method="POST" action="/students/edit">
            {% csrf_token %} {% for p in profile_list %}
            <div class="form-group">
              <label class="name">Name</label>
              <div>
                <input
                  type="text"
                  class="form-control input-lg"
                  name="name"
                  value="{{p.name}}"
                />
              </div>
            </div>
            <div class="form-group">
              <label class="phone_number">Phone Number</label>
              <div>
                <input
                  type="text"
                  class="form-control input-lg"
                  name="phone_number"
                  value="{{p.phone_number}}"
                />
              </div>
            </div>
            <div class="form-group">
              <label class="classes">Classes</label>
              <div>
                <input
                  type="text-box"
                  class="form-control input-lg"
                  name="classes"
                  value="{{p.classes}}"
                />
              </div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">
              Make Changes
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script>
    $("#edit").on("hide.bs.modal", function () {
      location.reload();
    });
  </script>

  {% if profile_list %}
  <ul class="list-group">
    {% for p in profile_list %}
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">
          <h4 style="text-align: center;">
            {{p.name}}
          </h4>
        </h3>
      </div>
      <div
        class="col-md-3 col-lg-3"
        align="center"
        style="margin-top: 2rem; margin-bottom: 2rem;"
      >
        <img
          src="{{ p.user.socialaccount_set.all.0.get_avatar_url }}"
          height="150"
          width="150"
        />
      </div>
      <div class="col-md-9 col-lg-9" style="margin-top: 2rem;">
        <table class="table table-user-information">
          <tbody>
            <tr>
              <td style="text-align: center;">Classes:</td>
              <td style="text-align: center;">{{p.classes}}</td>
            </tr>
            <tr>
              <td style="text-align: center;">Phone Number</td>
              <td style="text-align: center;">{{p.phone_number}}</td>
            </tr>
            <tr>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    {% endfor %}
  </ul>
  {% else %}
  <p>Your profile isn't in the database.</p>
  {% endif %}
</div>
</body>
<footer id="pfooter">
  <div>Quick Tutor | @ 2020</div>
  <a>Contact: 1-800-234-1234</a>
</footer>
{% endif %}
{% endfor %}
{% endif %}
</html>

students/templates/students/ratings.html
{% extends "./layout.html" %} {% block content %}

<link 
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh">
    <link  
      href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#rate">
    Make Rating
    </button>

<!-- Modal Stuff -->

<div class="modal" id="rate">
    <div class="modal-dialog">
      <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Rate This Tutor</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <!-- Modal body -->
        <div class="modal-body">
          <form id="rate" role="form" method="POST" action="{% url 'students:request_close' %}">
            {% csrf_token %}
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary active">
                  <input type="radio" name="options" id="1" autocomplete="off"> 1
                </label>
                <label class="btn btn-secondary">
                  <input type="radio" name="options" id="2" autocomplete="off"> 2
                </label>
                <label class="btn btn-secondary">
                  <input type="radio" name="options" id="3" autocomplete="off"> 3
                </label>
                <label class="btn btn-secondary">
                    <input type="radio" name="options" id="4" autocomplete="off"> 4
                  </label>
                  <label class="btn btn-secondary">
                    <input type="radio" name="options" id="5" autocomplete="off"> 5
                  </label>
              </div>
            <button type="submit" class="btn btn-success">Submit Rating</button>
          </form>
        </div>
      </div>
    </div>
  </div>


  {% endblock %}

students/templates/students/requests.html
{% extends "./layout.html" %} {% block content %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" />
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css" />
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<style>
  .modal-title {
    text-align: center;
    width: 100%;
  }

  form {
    text-align: center;
  }
</style>

<!DOCTYPE html>
<div align="center">
  <html lang="en">
  {% load static %}

  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'students/format.css' %}" />
    <title>Current Requests</title>
  </head>

  <body>
    {% if requests_list %} {% for request in requests_list %}
    <div class="card w-50" align="center">
      {% if request.status == "accept" %}
      <div class="card-header" style="background-color: #5cb85c;">
        <h4>
          Request for: {{request.tutor}}
        </h4>
      </div>
      {% endif %} {% if request.status == "No choice" %}
      <div class="card-header">
        <h4>
          Request for: {{request.tutor}}
        </h4>
      </div>
      {% endif %} {% if request.status == "deny" %}
      <div class="card-header" style="background-color: #d9534f;">
        <h4>
          Request for: {{request.tutor}}
        </h4>
      </div>
      {% endif %}
      <div class="card-body">
        <h4 class="card-title">Details:</h4>
        <h5 class="card-text">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Status: {{request.status}}
            </li>
            <li class="list-group-item">
              Time: {{request.time}}
            </li>
          </ul>
        </h5>
        <div>
          <a href="/tutors/profile/{{request.tutor}}" target="_blank" title="Opens in a new window"
            class="btn btn-primary">{{request.tutor}}'s profile</a>
        </div>
        <br />
        <div>
          {% if request.status == "accept" %} {% csrf_token %}
          <button type="button" onclick="save('{{request.id}}')" class="btn btn-danger" data-toggle="modal"
            data-target="#rate">
            Close Request
          </button>
          {% endif %}
          {% if request.status == "deny" %}
          <form action="{% url 'students:request_close' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="requ" value="{{request.id}}" />
            <input type="hidden" name="options" value="6" />
            <button type="submit" class="btn btn-danger">
              Close Request
            </button>
          </form>
          {%endif%}
        </div>
      </div>
    </div>
    <br />
    {% endfor %} {% else %}
    <h4>
      No current requests. Find a tutor on the homepage and request their
      help!
    </h4>
    {% endif %}
  </body>
  <br />
  <br />
  <br />

  </html>
</div>

<!-- Modal Stuff -->

<div class="modal" id="rate">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Rate This Tutor</h4>
        <button type="button" class="close" data-dismiss="modal">
          &times;
        </button>
      </div>
      <!-- Modal body -->
      <div class="modal-body">
        <form class id="rate" role="form" method="POST" action="{% url 'students:request_close' %}">
          {% csrf_token %}
          <div class="form-group">
            <div>
              <input type="hidden" id="requ" name="requ" />
            </div>
          </div>
          <div class="form-group">
            <div class="justify-content-center">
              <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary active">
                  <input type="radio" name="options" id="1" autocomplete="off" value="1" />
                  1
                </label>
                <label class="btn btn-secondary">
                  <input type="radio" name="options" id="2" autocomplete="off" value="2" />
                  2
                </label>
                <label class="btn btn-secondary">
                  <input type="radio" name="options" id="3" autocomplete="off" value="3" />
                  3
                </label>
                <label class="btn btn-secondary">
                  <input type="radio" name="options" id="4" autocomplete="off" value="4" />
                  4
                </label>
                <label class="btn btn-secondary">
                  <input type="radio" name="options" id="5" autocomplete="off" value="5" checked="checked" />
                  5
                </label>
              </div>
            </div>
          </div>
          <button type="submit" class="btn btn-success">Submit Rating</button>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  function save(a) {
    var req = document.getElementById("requ");
    requ.value = a;
  }
</script>

{% endblock %}