mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('students.urls')),
    path('admin/', admin.site.urls),
    path('tutors/', include('tutors.urls')),
    url(r'^accounts/', include('allauth.urls')),
]

tutors/urls.py
from django.urls import path
from . import views

app_name = 'tutors'

urlpatterns = [
    path('edit', views.edit_form, name='edit'),
    path('', views.home, name='home'),
    path('logout', views.logoutview, name='logout'),
    path('profile/<str:username>', views.ProfileView.as_view(), name='profile'),
    path('profile', views.ProfileView.as_view(), name='myprofile'),
    path('signup', views.signup_form, name='signup'),
    path('activate', views.activate, name='activate'),
    path('deactivate', views.deactivate, name='deactivate'),
    path('send_request/<str:username>', views.send_request, name='request'),
    path('requests', views.request_view, name='request_view'),
    path('request_action/', views.request_action, name='request_action'),
    path('request_close/', views.request_close, name='request_close')
]

tutors/models.py
from django.db import models
from django import forms
from django.conf import settings
from django.utils import timezone
import datetime
from django.contrib.auth.models import User
# from students.models import StudentSignup
from django.utils.translation import gettext as _

SUBJECT_CHOICES = (
    ('english','english'),
    ('engineering','engineering'),
    ('humanities','humanities'),
    ('language','language'),
    ('math', 'math'),
    ('social sciences','social sciences'),
    ('sciences','sciences'),
    ('other','other'),
)

PAY_CHOICES = (
    ('venmo', 'venmo'),
    ('cash', 'cash'),
    ('paypal', 'paypal'),
)


class TutorSignup(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=500, default="")
    phone_number = models.CharField(max_length=12, default="")
    classes = models.TextField(max_length=120, default="")
    subjects = models.CharField(max_length=120, choices=SUBJECT_CHOICES, default="")
    pay = models.CharField(max_length=12, default="")
    payment_method = models.CharField(max_length=120, choices=PAY_CHOICES, default="")
    longitude = models.DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)
    latitude = models.DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)
    status = models.BooleanField(default=False)
    rating = models.DecimalField(max_digits=3, decimal_places=2, blank=True, null=True)
    num_rates = models.IntegerField(default=0)

    def __str__(self):
        if self.phone_number==None:
            return "ERROR-NO PHONE NUMBER"
        return self.phone_number

class Request(models.Model):
    student = models.ForeignKey(User, related_name='students', on_delete=models.CASCADE)
    tutor = models.ForeignKey(User, related_name='tutors', on_delete=models.CASCADE)
    STATUS = (
       ('accept', _('Accept')),
       ('deny', _('Deny')),
       ('No choice', _('No choice')),
   )
    status = models.CharField(
       max_length=32,
       choices=STATUS,
       default='No choice',
   )
    time = models.DateTimeField('time sent')
     
    def __str__(self):
        return self.status

tutors/forms.py
from django import forms
 
from .models import TutorSignup
 
 
class TutorSignupForm(forms.ModelForm):
    class Meta:
        model = TutorSignup
        fields = ('name', 'phone_number', 'classes', 'subjects', 'pay', 'payment_method')
        required = ('name', 'phone_number', 'classes', 'subjects', 'pay', 'payment_method')
        labels = {
        "phone_number": "Phone Number",
        "classes": "Classes (ex. CS 3240, CS 2150)",
        "pay": "Pay (in $$)",
        "payment_method": "Payment Method"
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

tutors/views.py
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.views import generic
from django.shortcuts import render, get_object_or_404
from .models import TutorSignup, Request
from django.contrib import messages
from .forms import TutorSignupForm
from django.contrib.auth.decorators import login_required
from students import urls
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from django.contrib.auth import logout
from students.models import StudentSignup
from django.contrib.auth.models import User
import datetime
from django.urls import reverse
from uuid import uuid4

# getting the secret access token from .env file
from dotenv import load_dotenv
load_dotenv()
import os
ACCESS_TOKEN = os.getenv("ACCESS_TOKEN")

@login_required(login_url='students:landing')
def home(request):
    user = TutorSignup.objects.get(user=request.user)
    status = user.status
    latitude = user.latitude
    longitude = user.longitude
    return render(request, 'tutors/home.html', {'ACCESS_TOKEN': ACCESS_TOKEN, 'status': status, 'latitude': latitude, 'longitude': longitude}) 

def logoutview(request):
    user = TutorSignup.objects.get(user=request.user)
    user.longitude = None
    user.latitude = None
    user.status = False
    user.save()
    logout(request)
    return redirect('students:landing')

class ProfileView(LoginRequiredMixin, generic.ListView):
    login_url = 'students:landing'
    redirect_field_name = 'redirect_to'
    template_name = 'tutors/profile.html'
    context_object_name = 'profile_list'

    def get_context_data(self, **kwargs):
        try:
            context = super().get_context_data(**kwargs)
            user = StudentSignup.objects.get(user=self.request.user)
            context['hasother'] = 'yes'
            return context
        except:
            context['hasother'] = 'no'
            return context

    def get_queryset(self):
        try:
            request_user = User.objects.get(username=self.kwargs['username'])
            return TutorSignup.objects.filter(user=request_user)
        
        except:
            return TutorSignup.objects.filter(user=self.request.user)
    
@login_required(login_url='students:landing')
def activate(request):
    if request.method == 'POST':
        longitude = request.POST.get('long_form')
        latitude = request.POST.get('lat_form')
        user = TutorSignup.objects.get(user=request.user)
        user.longitude = longitude
        user.latitude = latitude
        user.status = True
        user.save()
        return HttpResponseRedirect('/tutors/')

@login_required(login_url='students:landing')
def deactivate(request):
    if request.method == 'POST':
        user = TutorSignup.objects.get(user=request.user)
        user.longitude = None
        user.latitude = None
        user.status = False
        user.save()
        return HttpResponseRedirect('/tutors/')

@login_required(login_url='students:landing')
def edit_form(request):
    if request.method == 'POST':
        name = request.POST['name']
        phone = request.POST['phone_number']
        classes = request.POST['classes']
        subjects = request.POST.get("subjects")  
        pay = request.POST['pay']
        payment_method = request.POST.get("payment_method")  
        user = TutorSignup.objects.get(user=request.user)
        user.name = name
        user.phone_number = phone
        user.classes = classes
        user.subjects = subjects
        user.pay = pay
        user.payment_method = payment_method
        user.save()
        return redirect('tutors:myprofile')
    else:
        form = TutorSignupForm()
    return render(request, 'tutors/edit.html', {'form': form})

@login_required(login_url='students:landing')
def signup_form(request):
    if request.method == 'POST':
        form = TutorSignupForm(request.POST)
        try:
            person = TutorSignup.objects.get(user=request.user)
            messages.error(request,'Tutor Account Already Exists For This User!')
            return redirect('/tutors/signup')
        except TutorSignup.DoesNotExist or IntegrityError or MultiValueDictKeyError: 
            if form.is_valid():
                name = request.POST['name']
                phone = request.POST['phone_number']
                classes = request.POST['classes']
                subjects = request.POST['subjects']            
                pay = request.POST['pay']
                longitude = None
                latitude = None
                status = False
                payment_method = request.POST['payment_method']
                user_object = TutorSignup.objects.create(user=request.user, name=name, phone_number = phone, classes = classes, subjects = subjects, pay = pay, payment_method = payment_method, longitude = longitude, latitude = latitude)
                user_object.save()
        return HttpResponseRedirect('/tutors')
    else:
        form = TutorSignupForm()
    return render(request, 'tutors/signup.html', {'form': form}) 

@login_required(login_url='students:landing')
def send_request(request, username):
    # this should be activated when the student clicks the "request" button
    # creates a new instance of a Request

    student = User.objects.get(username=request.user.username)

    request_user = User.objects.get(username=username)
    tutor = User.objects.get(username=username)

    time = datetime.datetime.now()
    r = Request.objects.create(student=student, tutor=tutor, time=time)
    r.save()

    return HttpResponseRedirect('/students/requests')

@login_required(login_url='students:landing')
def request_view(request):
    template_name = 'tutors/requests.html'
    context_object_name = 'requests_list'

    requests = Request.objects.filter(tutor=request.user).order_by('-time')

    return render(request, 'tutors/requests.html', {'requests_list': requests}) 

@login_required(login_url='students:landing')
def request_action(request):
    if request.method == 'POST':
        request_id = int(request.POST['request_id'])
        action = str(request.POST['action'])
        specific_request = Request.objects.get(pk=request_id)
        specific_request.status = action
        specific_request.save()
        return HttpResponseRedirect('/tutors/requests')

@login_required(login_url='students:landing')
def request_close(request):
    if request.method == 'POST':
        request_id = int(request.POST['request_id'])
        specific_request = Request.objects.get(pk=request_id)
        specific_request.delete()
        return HttpResponseRedirect('/tutors/requests')

tutors/templates/tutors/edit.html
<!doctype html>
<div style='text-align:center'>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Tutor Signup Form</title>
</head>
<h1>Tutor Edit Form</h1>
{% block body %}
<p ALIGN="center">
{% endblock %}</p>

tutors/templates/tutors/home.html
{% extends "./layout.html" %} {% block content %}

<html>
  {% load static %}
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="initial-scale=1,maximum-scale=1,user-scalable=no"
    />
    <script src="https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.js"></script>
    <link
      href="https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.css"
      rel="stylesheet"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Tutor Homepage</title>
  </head>
  <body>
    <style>
      .mapboxgl-marker {
        border: none;
        border-radius: 50%;
        cursor: pointer;
        padding: 0;
      }
      .coordinates {
        background: rgba(0, 0, 0, 0.5);
        color: #fff;
        position: absolute;
        bottom: 25px;
        left: 15px;
        padding: 5px 10px;
        margin: 0;
        font-size: 11px;
        line-height: 18px;
        border-radius: 3px;
        display: none;
      }
    </style>
    {% if status %}
    <div id="progress">
      <div class="progress">
        <div
          class="progress-bar progress-bar-striped bg-success"
          role="progressbar"
          style="width: 100%;"
          aria-valuenow="100"
          aria-valuemin="0"
          aria-valuemax="100"
        >
          Active
        </div>
      </div>
    </div>
    {% else %}
    <div id="progress">
      <div class="progress">
        <div
          class="progress-bar progress-bar-striped bg-danger"
          role="progressbar"
          style="width: 100%;"
          aria-valuenow="100"
          aria-valuemin="0"
          aria-valuemax="100"
        >
          Inactive
        </div>
      </div>
    </div>
    {% endif %}
    <pre type="hidden" id="coordinates" class="coordinates"></pre>
    <input type="hidden" name="long" id="long" />
    <input type="hidden" name="lat" id="lat" />
    <div id="map" style="width: 85%; height: 65%;"></div>
    <script>
      var ACCESS_TOKEN = "{{ACCESS_TOKEN}}";
      var tutor_lat = "{{latitude}}";
      var tutor_long = "{{longitude}}";
      var coordinates = document.getElementById("coordinates");

      if (navigator.geolocation) {
        // getting current position and creating a map centered at current position
        navigator.geolocation.getCurrentPosition(
          function (position) {
            mapboxgl.accessToken = ACCESS_TOKEN;
            var long = 0.0;
            var lat = 0.0;
            // if tutor is active, set the marker to be at the tutor's correct location from the model
            if (isNaN(tutor_lat)) {
              long = position.coords.longitude;
              lat = position.coords.latitude;
            } else {
              lat = tutor_lat;
              long = tutor_long;
            }

            var map = new mapboxgl.Map({
              container: "map",
              style: "mapbox://styles/mapbox/streets-v11",
              center: [long, lat],
              zoom: 14,
            });

            if (isNaN(tutor_lat)) {
              // if tutor is not active, can drag the marker
              var marker = new mapboxgl.Marker({
                draggable: true,
              })
                .setLngLat([long, lat])
                .setPopup(
                  new mapboxgl.Popup({ offset: 25 }).setHTML("<div>" + "You")
                )
                .addTo(map);
              document.getElementById("long").value = long;
              document.getElementById("lat").value = lat;
            } else {
              // if tutor is active, cannot drag the marker
              var marker = new mapboxgl.Marker()
                .setLngLat([long, lat])
                .setPopup(
                  new mapboxgl.Popup({ offset: 25 }).setHTML("<div>" + "You")
                )
                .addTo(map);
              document.getElementById("long").value = long;
              document.getElementById("lat").value = lat;
            }

            // can drag the marker to your actual location and displays lat, long
            function onDragEnd() {
              var lngLat = marker.getLngLat();
              document.getElementById("long").value = lngLat.lng;
              document.getElementById("lat").value = lngLat.lat;
            }
            marker.on("dragend", onDragEnd);
          },
          function (error) {
            alert("Enable location services.");
          },
          { maximumAge: 10000, timeout: 5000, enableHighAccuracy: true }
        );
      } else {
        alert("Location services not available.");
      }
    </script>
    {% if status %}
    <div id="activate">
      <div id="button">
        <button
          type="button"
          class="btn btn-danger"
          data-toggle="modal"
          data-target="#exampleModal"
          id="deactivate"
        >
          I'm done tutoring!
        </button>
      </div>
    </div>
    <br />
    <div
      class="modal fade"
      id="exampleModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
              Tutoring status
            </h5>
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Are you sure you're done tutoring?
          </div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-dismiss="modal"
            >
              No
            </button>
            <form action="/tutors/deactivate" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger" value="Submit">
                Yes - I'm done tutoring!
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% else %}
    <div id="activate">
      <div id="button">
        <button
          type="button"
          class="btn btn-success"
          data-toggle="modal"
          data-target="#exampleModal"
          id="activate"
        >
          I'm ready to tutor!
        </button>
      </div>
    </div>
    <br />
    <div
      class="modal fade"
      id="exampleModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
              Tutoring status
            </h5>
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Is the marker at your current location?
          </div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-dismiss="modal"
            >
              No - I will move the marker!
            </button>
            <!-- form to submit current location -->
            <form action="/tutors/activate" method="POST">
              {% csrf_token %}
              <input type="hidden" name="long_form" id="long_form" />
              <input type="hidden" name="lat_form" id="lat_form" />
              <button type="submit" class="btn btn-success" value="Submit">
                Yes - I'm ready to tutor!
              </button>
            </form>
            <!-- script to grab current coordinates from html element -->
            <script>
              $("#activate").click(function () {
                var long = $("#long").val();
                var lat = $("#lat").val();
                document.getElementById("long_form").value = long;
                document.getElementById("lat_form").value = lat;
              });
            </script>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  </body>
</html>

{% endblock %}

tutors/templates/tutors/layout.html
<html>
  {% load static %}
  <head>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'tutors/format.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css"
      rel="stylesheet"
      id="bootstrap-css"
    />
  </head>
  <div id="page">
    <div id="wrapper">
      <header class="polls-header">
          <div class="flex-grid">
            <div class="col1">
              <a href="/tutors">
                <img src="/../static/images/logo.jpg" width="50" height="50" alt="">
              </a>
            </div>
            <div class="col1">          
              <nav class="navbar navbar-light" style="background-color: #ffffff;">
              <a class="nav-link" href="/tutors"><h4>Home</h4></a>
              <a class="nav-link" href="{% url 'tutors:request_view' %}"
              >
              <h4>
                Requests
              </h4></a
              >
              <a class="nav-link" href="{% url 'tutors:profile' user.username %}"
              ><h4>
                Tutor Profile
              </h4></a
              >
              </nav>
            </div>
            <div class="col3">
            <nav class="navbar navbar-light" style="background-color: #ffffff;">
              {% if user.is_authenticated %}
                <form action="{% url 'tutors:logout'%}">
                  <button class="btn btn-outline-success my-2 my-sm-0" href="{% url 'tutors:logout'%}"
                    ><h4>Logout</h4></a
                  >
                </form>
              {% endif %}
            </nav>
          </div>
        </div>
      </header>
      <br />
      <body id="body">
        {% block content %} {% endblock %}
      </body>
    </div>
  <footer>
    <div>Quick Tutor | @ 2020</div>
    <a>Contact: 1-800-234-1234</a>
  </footer>
  </div>
</html>

tutors/templates/tutors/requests.html
{% extends "./layout.html" %} {% block content %}

<!DOCTYPE html>
<div align="center">
  <html lang="en">
  {% load static %}

  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'tutors/format.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Current Requests</title>
  </head>

  <body ALIGN="center">
    {% if requests_list %} {% for request in requests_list %}
    {%if request.status != "deny"%}
    <div class="card w-50" align="center">
      {% if request.status == "accept" %}
      <div class="card-header" style="background-color: #5cb85c;">
        <h4>
          Request from: {{request.student}}
        </h4>
      </div>
      {% endif %} {% if request.status == "No choice" %}
      <div class="card-header">
        <h4>
          Request from: {{request.student}}
        </h4>
      </div>
      {% endif %} {% if request.status == "deny" %}
      <div class="card-header" style="background-color: #d9534f;">
        <h4>
          Request from: {{request.student}}
        </h4>
      </div>
      {% endif %}
      <div class="card-body">
        <h4 class="card-title">Details:</h4>
        <h5 class="card-text">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Status: {{request.status}}
            </li>
            <li class="list-group-item">
              Time: {{request.time}}
            </li>
          </ul>
        </h5>
        <a href="/students/profile/{{request.student}}" target="_blank" title="Opens in a new window"
          class="btn btn-primary">{{request.student}}'s profile</a>
      </div>
      {% if request.status == "No choice" %}
      <form action="{% url 'tutors:request_action' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="request_id" value="{{request.id}}" />
        <input type="hidden" name="action" value="accept" />
        <button type="submit" class="btn btn-success">
          Accept
        </button>
      </form>
      <form action="{% url 'tutors:request_action' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="request_id" value="{{request.id}}" />
        <input type="hidden" name="action" value="deny" />
        <button type="submit" class="btn btn-danger">
          Deny
        </button>
      </form>
      {% else %}
      <div class="card-footer" style="background-color: #5cb85c;">
        Accepted! Waiting For Student Rating
      </div>
      {% endif %}
    </div>
    <br />
    {%endif%}
    {% endfor %}
    {% else %}
    <h4>No current requests. Keep your eye out for student requests!</h4>
    {% endif %}
  </body>
  <br />
  <br />
  <br />

  </html>
</div>

{% endblock %}

tutors/templates/tutors/signup.html
<!doctype html>
<div style='text-align:center'>
<html lang="en">
  {% load static %}
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'tutors/format.css' %}"
    />
    <title>Tutor Signup Form</title>
</head>
<div id="top">
  <div class="container">
    <div class="row">
      <a href="/">
        <div class="col">
          <img
            src="/../static/images/logo.jpg"
            width="50"
            height="50"
            alt=""
          />
        </div>
      </a>
    </div>
  </div>
</div>
{% for message in messages %}
{% if message.tags == "error" %}
<div class="alert alert-danger">
  <a class="close" href="#" data-dismiss="alert">×</a>
    {{message}}
</div>
{% endif %}
{% endfor %}
<div id="page">
  <div id="wrapper">
    <body id="body">
{% load crispy_forms_tags %}
<h1>Tutor Signup Form</h1>
<p ALIGN="center"><form action="/tutors/signup" method="POST">
    {% csrf_token %}
    <div class = "form69">
      {{ form|crispy }}
    </div>
    <button type="submit" class="btn btn-success">Submit</button>
</form>
</p>
<div id="lfooter">
  <div>Quick Tutor | @ 2000</div>
  <a>Contact: 1-800-234-1234</a>
</div>
</html>